services:

  test:
    image: ghcr.io/tboulund-dls/happy-headlines-demo:latest
    build:
      context: demo
      dockerfile: Dockerfile
    depends_on:
      - mailpit

  structurizr:
    image: structurizr/lite
    ports:
      - "8080:8080"
    volumes:
      - ./docs:/usr/local/structurizr

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - mailpit-data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbitmq_management load_definitions "/etc/rabbitmq/definitions.json"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - ./rabbitmq-definitions.json:/etc/rabbitmq/definitions.json

  featurehub:
    image: featurehub/party-server:latest
    restart: always
    volumes:
      - featurehub-h2-data:/db
    ports:
      - 8085:8085
        
  profanityapi:
    image: profanityapi
    build:
      context: .
      dockerfile: profanity-service/Dockerfile
    environment:
      - mongoconn=random
      - redishconn=randomredish
    ports:
      - "9081:8081"
    depends_on:
      - profanitydb
      - profanitycache
  
  profanitydb:
    image: mongodb/mongodb-community-server:7.0.5-ubuntu2204
    environment:
      - MONGO_INITDB_ROOT_USERNAME=profanityuser
      - MONGO_INITDB_ROOT_PASSWORD=!Profanitypass123
    volumes:
      - profanitydata:/var/lib/mongodb/data
  
  profanitycache:
    image: redis/redis-stack-server:latest
    
    
      
    

volumes:
  mailpit-data:
  rabbitmq-data:
  featurehub-h2-data:
  profanitydata: