networks:
  article-network:
    driver: bridge
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: article-publisher-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./definitions.json:/etc/rabbitmq/definitions.json
    restart: unless-stopped
    networks:
      - article-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: article-publisher-api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - rabbitmq
    networks:
      - article-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: article-publisher-ui
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - article-network
